### ISSUE TITLE
Shorthand notation

### ISSUE THREAD

**Issue by unboundmusic** [pimentel/voicecode-cyberduck#1]
https://github.com/pimentel/voicecode-cyberduck/blob/master/package.coffee#L1

This pattern of creating a package and a scope with the same name is very common, so we auto generate scope if the package needs it, which simplifies the package code. It can be:

```coffeescript
pack = Packages.register
  name: 'cyberduck-ftp'
  description: 'An interface for the CyberDuck FTP client.'
  applications: ['ch.sudo.cyberduck']

pack.implement
  'command-line:change-directory': ->
    @key 'g', 'command'
```

And it will apply the scope to all implementations by that package, unless specified otherwise

**Comment by pimentel** [comment]
Thanks! addressed in latest version.
